### ISSUE TITLE
Why Reset method of Barrier interface is needed?

### ISSUE THREAD

**Issue by aQuaYi** [marusama/cyclicbarrier#1]
[Barrier Class (System.Threading) | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/system.threading.barrier?redirectedfrom=MSDN&view=netframework-4.8#methods) do not have `Reset` method.

and 

[CyclicBarrier (Java SE 9 & JDK 9 )](https://docs.oracle.com/javase/9/docs/api/java/util/concurrent/CyclicBarrier.html#reset--) say 
>reset
public void reset​()
Resets the barrier to its initial state. If any parties are currently waiting at the barrier, they will return with a BrokenBarrierException. Note that resets after a breakage has occurred for other reasons can be complicated to carry out; threads need to re-synchronize in some other way, and choose one to perform the reset. It may be preferable to instead create a new barrier for subsequent use.

So I think we don't need the `Reset` method.

**Comment by marusama** [comment]
That is by design.
